# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Open Credit X' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Open Credit X
  pod 'AWSCore', '~> 2.9.0'

  target 'Open Credit XTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Open Credit XUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
